### ISSUE TITLE
在线构建报错“没有可用的docker server”

### ISSUE THREAD

**Issue by faymi** [dromara/Jpom#33]
DSL 脚本：
```
# 基础镜像 目前仅支持 ubuntu-latest
runsOn: ubuntu-latest
# 使用哪个 docker 构建,填写 docker 标签 默认查询可用的第一个,如果 tag 查询出多个也选择第一个结果
#fromTag: master
# version 需要在对应镜像源中存在
# java 镜像源 https://mirrors.tuna.tsinghua.edu.cn/Adoptium/
# maven 镜像源 https://mirrors.tuna.tsinghua.edu.cn/apache/maven/maven-3/
# node 镜像源 https://registry.npmmirror.com/-/binary/node/
steps:
  - uses: node
    version: 16.3.0
#  - uses: go
#    version: 1.17.6
#  - uses: python3
#    version: 3.6.6
# 将容器中的文件缓存到 docker 卷中
  - uses: cache
    path: ${JPOM_WORKING_DIR}/mortgage-calculator/node-modules
  - run: npm config set registry https://registry.npmmirror.com
# 内置变量 ${JPOM_WORKING_DIR} ${JPOM_BUILD_ID}
  - run: cd  ${JPOM_WORKING_DIR}/mortgage-calculator && npm i && npm run build
# 宿主机目录和容器目录挂载 /host:/container:ro
# binds:
#  - /Users/user/.m2/settings.xml:/root/.m2/
# 宿主机文件上传到容器 /host:/container:true
# dirChildrenOnly = true will create /var/data/titi and /var/data/tata dirChildrenOnly = false will create /var/data/root/titi and /var/data/root/tata
# copy:
#  - /Users/user/.m2/settings.xml:/root/.m2/:false
# 给容器添加环境变量
env:
  NODE_OPTIONS: --max-old-space-size=900
```
报错：
![image](https://user-images.githubusercontent.com/20684621/215730486-fd407e63-249d-4308-99b9-a5ff067cf145.png)
